#ifndef EMPLOYEE_H
#define EMPLOYEE_H

#include <QMainWindow>
QT_BEGIN_NAMESPACE
namespace Ui {
class gsecurite;
}
QT_END_NAMESPACE
class employee : public QMainWindow
{
    Q_OBJECT

public:
    explicit employee(QWidget *parent = nullptr);  // Constructor
    ~employee();  // Destructor

private slots:
    void on_pushButton_ajouter_clicked();
    void on_pushButton_supprimer_clicked();
    void on_tableView_clicked(const QModelIndex &index);
    void on_pushButton_modifier_clicked();

private:
    Ui::employee *ui;  // Pointer to the Ui::employee class generated by uic
    employee *emp;     // Instance for managing employee-related actions
};

#endif // EMPLOYEE_H
